### ISSUE TITLE
INACTIVE and BACKGROUND state is not working on Android?

### ISSUE THREAD

**Issue by xingsuo** [bamlab/redux-enhancer-react-native-appstate#4] opened 2017-11-30 20:41 UTC
Hi, 

I am trying to use this in both iOS and android platform. Based on my test, the INACTIVE and BACKGROUND action are working on iOS but not working properly on Android. But FOREGROUND action is working on both platform.

Does anyone else meet the same issue?

Thanks,
Max

**Comment by Almouro** [comment] 2017-12-11 20:30
Hi @xingsuo, thanks for posting an issue! :)

I saw no problems on my end. What is the device and OS you're using?

**Comment by Almouro** [comment] 2018-03-10 20:26
@xingsuo closing this due to low activity on this issue, feel free to reopen if the problem is still there for you!

**Closed by Almouro** 2018-03-10 20:26 UTC
